### Create Policy
POST http://localhost:8080/api/v1/lambda/policies
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwZSI6IkpXVCJ9.eyJ1c2VySWQiOiJmN2I4Y2FkZC05MmNiLTQ4MzAtYTU2NS1hMWM5MDM1OTdmYzYiLCJpYXQiOjE3MTE5OTY4MDB9.
Content-Type: application/json

{
  "account_id": "user-id",
  "principal_id": "lambda-id",
  "resource_type": "s3",
  "resource_id": "bucket/images/*",
  "action": "DeleteObject"
}

### Update Policy
PUT http://localhost:8080/api/v1/lambda/policies/policy-id
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwZSI6IkpXVCJ9.eyJ1c2VySWQiOiJmN2I4Y2FkZC05MmNiLTQ4MzAtYTU2NS1hMWM5MDM1OTdmYzYiLCJpYXQiOjE3MTE5OTY4MDB9.
Content-Type: application/json

{
  "account_id": "user-id",
  "principal_id": "lambda-id",
  "resource_type": "s3",
  "resource_id": "bucket/images/*",
  "action": "GetObject"
}

### Get Policy
GET http://localhost:8080/api/v1/lambda/policies/policy-id
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwZSI6IkpXVCJ9.eyJ1c2VySWQiOiJmN2I4Y2FkZC05MmNiLTQ4MzAtYTU2NS1hMWM5MDM1OTdmYzYiLCJpYXQiOjE3MTE5OTY4MDB9.

### Delete Policy
DELETE http://localhost:8080/api/v1/lambda/policies/policy-id
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwZSI6IkpXVCJ9.eyJ1c2VySWQiOiJmN2I4Y2FkZC05MmNiLTQ4MzAtYTU2NS1hMWM5MDM1OTdmYzYiLCJpYXQiOjE3MTE5OTY4MDB9.
